name: carbon_admin
description: Admin panel for Go backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.9.0
  file_picker: ^10.3.2
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  http: ^1.2.2
  equatable: ^2.0.7
  json_annotation: ^4.10.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.11.0

flutter:
  uses-material-design: true
